[package]
name = "bevy-suis"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_mod_xr = { git = "https://github.com/awtterpip/bevy_oxr.git"}
schminput = { git = "https://github.com/Schmarni-Dev/Schminput.git", features = ["xr"], branch = "bevy_0.15"}

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_mod_openxr = { git = "https://github.com/awtterpip/bevy_oxr.git"}
openxr = { version = "0.19", default-features = false }

[dev-dependencies]
bevy_xr_utils = { git = "https://github.com/awtterpip/bevy_oxr.git"}

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
