[package]
name = "bevy-suis"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = []
xr = ["schminput/xr"]

[dependencies]
bevy = { version = "0.17", features = [
	"bevy_color",
	"bevy_camera",
	"bevy_gizmos",
], default-features = false }
bevy_mod_xr = "0.4"
schminput = { version = "0.4" }

[dev-dependencies]
bevy_mod_openxr = "0.4"
openxr = "0.19"
bevy = { version = "0.17", default-features = true }


[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[workspace]
members = ["bevy-suis-explicit-method-data"]
