[package]
name = "bevy-suis-explicit-method-data"
version = "0.2.0"
edition = "2024"

[dependencies]
bevy = "0.16"
schminput = { git = "https://github.com/Schmarni-Dev/schminput", features = [
	"xr",
], branch = "main" }
bevy-suis.path = ".."
